---
- name: Install nginx+madiadb+php-fpm stack on centos 
  hosts: localhost
  become: true

  tasks:
  - name: update centos 
    yum:
     name: update -y 
     state: yes 
   
  tasks:
  - name: install htop
    yum:  
      name: htop
      state: started

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Enable nginx
    systemd:
      name: nginx
      enabled: yes

  - name: Insert Index.php Devops test
    template:
      src: index.php
      dest: /usr/share/nginx/html/index.php

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: Insert MariaDB repo file
    template:
      src: mariadb.repo
      dest: /etc/yum.repos.d/mariadb.repo

  - name: Install MariaDB-server
    yum:
      name: mariadb-server
      state: present

  - name: Start MariaDB
    service:
      name: mariadb
      state: started

  - name: Enable mariadb
    systemd:
      name: mariadb
      enabled: yes

  - name: Install php
    yum:
      name: php
      state: present

  - name: Install php-mysql
    yum:
      name: php-mysql
      state: present

  - name: Install php-fpm
    yum:
      name: php-fpm
      state: present

  - name: Ensure "cgi.fix_pathinfo=0" in /etc/php.ini
    ini_file:
      path: /etc/php.ini
      section: PHP
      option: cgi.fix_pathinfo
      value: 0

  - name: Ensure "listen = /var/run/php-fpm/php-fpm.sock" in /etc/php-php.d/www.conf
    ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: listen
      value: /var/run/php-fpm/php-fpm.sock

  - name: Ensure "listen.owner = nobody" in /etc/php-php.d/www.conf
    ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: listen.owner
      value: nobody

  - name: Ensure "listen.group = nobody" in /etc/php-php.d/www.conf
    ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: listen.group
      value: nobody

  - name: Ensure "user = nginx" in /etc/php-php.d/www.conf
    ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: user
      value: nginx

  - name: Ensure "group = nginx" in /etc/php-php.d/www.conf
    ini_file:
      path: /etc/php-php.d/www.conf
      section: www
      option: group
      value: nginx

  - name: Start php-fpm
    service:
      name: php-fpm
      state: started

  - name: Enable php-fpm
    systemd:
      name: php-fpm
      enabled: yes

  - name: Insert nginx conf
    template:
      src: nginx.conf
      dest: /etc/nginx/conf.d/default.conf

  - name: Insert phpinfo.php page
    template:
      src: phpinfo.php
      dest: /usr/share/nginx/html/phpinfo.php



